#pragma once
#define CHICKEN_MOVEMENT_AMOUNT 30
#define CHICKEN_SIZE_WIDTH 30
#define CHICKEN_SIZE_HEIGHT 30

#define HUMAN_MOVEMENT_SPEED 30
#define HUMAN_SIZE_HEIGHT 60
#define HUMAN_SIZE_WIDTH 30

#define WINDOW_WIDTH 750
#define WINDOW_HEIGHT 450

#define MAX_SCORE 1000

#define WINDOW_TITLE "FRIED CHICKEN"
