#pragma once
#define CHICKEN_MOVEMENT_AMOUNT 90
#define CHICKEN_SIZE_WIDTH 90
#define CHICKEN_SIZE_HEIGHT 90

#define HUMAN_MOVEMENT_SPEED 90
#define HUMAN_SIZE_HEIGHT 180
#define HUMAN_SIZE_WIDTH 90

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define MAX_SCORE 1000

#define WINDOW_TITLE "FRIED CHICKEN"
