#pragma once
#define CHICKEN_MOVEMENT_AMOUNT 80
#define CHICKEN_SIZE_WIDTH 80
#define CHICKEN_SIZE_HEIGHT 80

#define HUMAN_MOVEMENT_SPEED 0.2
#define HUMAN_SIZE_HEIGHT 120
#define HUMAN_SIZE_WIDTH 60

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define WINDOW_TITLE "FRIED CHICKEN"
